### PR TITLE
More features for integration with UE5

### PR DESCRIPTION
**Pull request by MaxiCabanas**
# - [Implemented Button in toolbar and developer settings.](https://github.com/gwaredd/MarkdownAsset/commit/409509267cd33baa2c597aaa7bad91b403a77c5c)

- Now there is a button in the LevelEditor to open a ProjectDocumentation main file. This file can be set in the DeveloperSettings (ProjectSettings/MarkdownAssetSettings). The main idea behind this feature is to easily access to the documentation without the need to search for it in the ContentDrawer.

Future updates to this feature includes make the button optional with an editor setting and more advance features (See [Create MarkdownAsset file from UI in editor.](https://github.com/gwaredd/MarkdownAsset/commit/56ee9a2c6a8724817a120e13400c86e7753af538) for references)

# - [Implemented new AssetDefinition aproach to custom asset actions.](https://github.com/gwaredd/MarkdownAsset/commit/8da8bb3b853c6b75123396ea001d8a43e982ce36)

Migrated custom Asset actions from old FAssetTypeActions_Base system to the newer UAssetDefinitionDefault system, avoiding possibles deprecations in the near future. This also helps keeping cleaner the module's MarkdownAssetEditorModule

Created a Icon.h file, so we can give the used engine native icons a descriptive name and easy access.

# - [Editor notification for when the main file is not set now shows a link to the plug-in settings page.](https://github.com/gwaredd/MarkdownAsset/commit/efe335fda079a92ede1916e2e3c65d71cdc71390)

Added an editor notification for when the user is trying to access the project documentation main file from the level editor window but the file is not set yet. This will be replaces in the future with a dialog for asset selection/creation (See [Create MarkdownAsset file from UI in editor.](https://github.com/gwaredd/MarkdownAsset/commit/56ee9a2c6a8724817a120e13400c86e7753af538) for references)

This feature has some other implications to the project.
- Created a namespace for static helper functions. MarkdownAssetStatics
- Added a function for diplaying an editor notification, It supports a hyperlinks.

# - [Create MarkdownAsset file from UI in editor.](https://github.com/gwaredd/MarkdownAsset/commit/56ee9a2c6a8724817a120e13400c86e7753af538)

- Now its possible to [link MarkdownAssets with other Assets](https://github.com/gwaredd/MarkdownAsset/commit/2b219eee006c561a3a43c6e181d338664512b9f8). For now this association occurs through a TMap in ProjectSettings, but it may be replaced in the future by a better way.
- Now there is a new button in the Asset Editor Window that lets the user open a MarkdownAsset associated with the asset is currently open. 
- If there is no MarkdownAsset file for the current asset when the user tries to open it, a dialog is opened so the user can create a new file. The name of the new asset will be create as: default prefix, plus the current open asset's name. Default prefix can be set in the ProjectSettings. There is also an option to make new files's erase the current prefix of open asset.
So a new MarkdownAsset for *BP_MyBlueprint* with the default settings will be called *MD_MyBlueprint*.
- MarkdownAssets created this way will also include a title line (h1) with the original name of the linked asset.
- There is now a DefaultDocumentationFolder setting, that lets the user define a folder inside Content folder to hold the newly created MarkdownAssets.

Some other changes made to the project with this feature:

- Splite the file MarkdownAssetEditorModule.cpp into two files (.h and .cpp) to have a more clean view of the code and better comply with the C++ guidelines
- Created new files to hold the definitions for custom log channels for the project. In the future more channels will be defined when proper data loggin is implemented for the project.

### CODE REVIEW

**Comment by MaxiCabanas** [comment]
@gwaredd 
I’m trying to create a comprehensive roadmap for my intended changes to this plug-in. I would certainly love to know if you personally have any plans for this plug-in in the future.

**Comment by gwaredd** [comment]
Looks good, nice functionality :) I added a null check to fix a crash I had and undef'd a LOCTEXT_NAMESPACE to fix a compile warning.

**Comment by MaxiCabanas** [comment]
Okay, so we are aligned!

I was planning to do some research on the best way to implement a search
feature but I was thinking about implementing some kind of tag system.
Maybe it would be better to directly start with content searching that
we know for sure would be useful.

After this upgrade in the UX I was thinking of implementing some kind of
"link visualization", nothing too fancy like the Graph View of Obsidian but
a custom editor window that lets the user visualize somehow the global
state of the documentation, maybe just a list. could even have a few
categories in that window and be a common point of "documentation status
reference".

Another game changer feature we could take advantage of is using YAML to
store and use metadata on the markdown files. As YAML is very popular and
widely used we could provide more compatibility importing/exporting from
Obsidian or or Notion (I think Notion doesn't export databases as YAML
natively, so users must rely on 3rd party open source solutions).

**Comment by gwaredd** [comment]
The Obsidian graph view might be overkill 🙂 But I agree with the sentiment, right now any documentation is little more than a loose collection of files. Some overview would go a long way to make them feel more connected and cohesive.

The simplest thing that could possibly work might be a "table of contents". The assets are already hierarchical in the project structure, so showing that hierarchy might be a quick first step. This could be added as a drop down or expandable section the web view so it's available when editing files rather than a separate editor window necessarily. 

What kind of metadata do you have in mind? The UE assets already have metadata and as a the markdown assets are just assets we can always add to them if UE doesn't provide what we need. Keeping the metadata with the asset rather than a separate file seems cleaner to me. However I can see the value in being able to import/export metadata as YAML between external apps like notion.

**Pull request merged**
